module-name: gardener-syncer
kind: kyma
bdba:
  - europe-docker.pkg.dev/kyma-project/prod/gardener-syncer:latest
mend:
  language: golang-mod
  exclude:
    - "**/*_test.go"
checkmarx-one:
    preset: go-default
    exclude:
        - '**/*_test.go'
