name: all-checks-passed
on:
  pull_request:
    types:
      [
        opened,
        synchronize,
        reopened,
        ready_for_review,
        edited,
        unlabeled,
        labeled,
        milestoned,
      ]

jobs:
  all-checks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: read
    steps:
      - uses: wechuli/allcheckspassed@c31fdf90d5379db0e370c8b3ff76cea07b379303
        with:
          delay: '3'
          retries: '30'
          polling_interval: '1'