name: Gardener Syncer Release

on:
  push:
    tags:
      - '*'  # Trigger on tag pushes

jobs:
  run-release-tests:
    permissions:
      contents: read
    uses: ./.github/workflows/run-tests.yaml

  generate-release:
    needs: run-release-tests
    if: needs.run-release-tests.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating releases and uploading assets
    steps:
      - name: Create Release and Generate Notes
        uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
